- .github/workflows/tests.yml
- .readthedocs.yml
- lsstdesc_diffsky/tests/test_setup.py
- requirements.txt
PR sets up CI testing and an RTD build of the docs
> Add rtd.yml and testing workflow

- .github/workflows/tests.yml
Modified test.yml to include a scheduled run of the CI tests
> Code refactor test docs

- lsstdesc_diffsky/constants.py
- lsstdesc_diffsky/tests/test_constants.py
WIP PR implementing constants.py
@evevkovacs
> Define constants module

- lsstdesc_diffsky/io_utils/load_sfh.py
- lsstdesc_diffsky/io_utils/tests/test_load_sfh.py
Add retrieve_diffstar_data function to new io_utils subdirectory
> Create io_utils subdirectory

- .github/workflows/tests.yml
Add codecov coverage upload to tests.yml
> Add codecov coverage upload to tests.yml

- lsstdesc_diffsky/constants.py
- lsstdesc_diffsky/tests/test_constants.py
Included default values for SED_params in constants.py instead of hard-coding them in the production module. Added a test to make sure that they weren't changed.
> Added more constants and tested them

- .github/workflows/readthedocs.yml
- .readthedocs.yml
- README.rst
- docs/source/citation.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/reference.rst
- lsstdesc_diffsky/ellipticity_modeling/__init__.py
- lsstdesc_diffsky/ellipticity_modeling/ellipticity_model.py
Here are some startup documents, mostly copied from dsps documentation. Appropriate pages are produced except that the  existing doc strings from code called in the API reference are not being rendered. I haven't been able to spot the error, nor has some googling given me any useful hints.
> Docs update

- lsstdesc_diffsky/photometry/load_filter_data.py
Adds option to read in throughput files used by ImSim
> Add option to use lsst throughputs used by ImSim

- scripts/mock_production/run_diffsky_healpix_production.py
- scripts/mock_production/run_mpi_hpx_production.sh
- scripts/mock_production/submit_mpi_group.sh
Driver python script has been modified to use mpi4py and production and submission shell scripts have been modified accordingly. Some minor improvements on automating the number of ranks requested could be added, but for now, the code has been tested and runs with no problem.
> Mpi4py tests

- docs/source/index.rst
Add link to source code on opening page of docs
> Add link to source code on opening page of docs

- lsstdesc_diffsky/diffstarpop/diffstar_sfh.py
Update calls to diffstar according to https://github.com/ArgonneCPAC/diffstar/pull/30
> Update calls to diffstar

- .readthedocs.yml
- docs/source/citation.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/requirements.txt
- docs/source/rtd_environment.yaml
Use conda yaml to specify environment in docs build
This PR replaces #45.
> Use conda yaml to specify environment in docs build

- README.rst
- pyproject.toml
> Update dependencies in pyproject.toml to include diffsky

- .github/workflows/tests.yml
- lsstdesc_diffsky/photometry/tests/test_photometry_lc_interp.py
- lsstdesc_diffsky/write_mock_to_disk.py
- requirements.txt
Rename DEFAULT_MZR_PDICT to DEFAULT_MET_PDICT in accord with https://github.com/ArgonneCPAC/dsps/pull/71
> Rename DEFAULT_MZR_PDICT to DEFAULT_MET_PDICT according to dsps update

- lsstdesc_diffsky/defaults.py
- lsstdesc_diffsky/sed/sed_kernels.py
- lsstdesc_diffsky/sed/tests/test_sed_kernels.py
Bring in a convenience function for computing the restframe SED of a dfifsky galaxy
> calc_rest_sed_singlegal convenience function

- lsstdesc_diffsky/__init__.py
- lsstdesc_diffsky/param_data/__init__.py
- lsstdesc_diffsky/param_data/param_reader.py
- lsstdesc_diffsky/param_data/tests/test_param_reader.py
Add convenience function that loads all the parameter dictionaries associated with `roman_rubin_2023`
@evevkovacs
> Add convenience function that loads all the parameter dictionaries associated with `roman_rubin_2023`

- lsstdesc_diffsky/sed/sed_kernels.py
- lsstdesc_diffsky/sed/tests/test_sed_kernels.py
Add convenience function calc_rest_sed_galpop
> Add convenience function calc_rest_sed_galpop

- lsstdesc_diffsky/sed/sed_kernels.py
Add forgotten factor of Mstar multiplying the convenience functions in sed_kernels.py
> Fix bug in SED convenience functions

- docs/source/demo_roman_rubin_2023_seds.ipynb
- lsstdesc_diffsky/__init__.py
- lsstdesc_diffsky/io_utils/__init__.py
- lsstdesc_diffsky/io_utils/load_diffsky_healpixel.py
- lsstdesc_diffsky/io_utils/tests/test_load_diffsky_healpixel.py
- lsstdesc_diffsky/param_data/__init__.py
- lsstdesc_diffsky/param_data/param_reader.py
- lsstdesc_diffsky/param_data/tests/test_param_reader.py
- lsstdesc_diffsky/sed/tests/test_disk_bulge_sed_kernels.py
- lsstdesc_diffsky/sed/tests/test_sed_kernels.py
Add convenience function for loading single healpixel
> Add convenience function for loading single healpixel

- docs/source/demo_roman_rubin_2023_seds.ipynb
- lsstdesc_diffsky/io_utils/load_diffsky_healpixel.py
- lsstdesc_diffsky/sed/tests/test_sed_kernels.py
> Add unrendered notebook

- docs/source/demo_roman_rubin_2023_seds.ipynb
- docs/source/demos.rst
Reinstate demo notebook into docs
> Reinstate notebook

- lsstdesc_diffsky/photometry/photometry_kernels.py
- lsstdesc_diffsky/photometry/tests/test_photometry_kernels.py
Add convenience functions calc_photometry_galpop
> Add convenience functions calc_photometry_galpop

- docs/source/demo_roman_rubin_2023_seds.ipynb
Update sed notebook with example calculations of both individual and populations of SEDs
> Update docs notebook on disk/bulge/knot SED calculations

- lsstdesc_diffsky/io_utils/load_diffsky_healpixel.py
Add patlist feature to load_healpixel function so that only a subset of available columns can be loaded at a time.
> Add patlist feature to load_healpixel function

- docs/source/demo_roman_rubin_2023_seds.ipynb
- lsstdesc_diffsky/io_utils/load_diffsky_healpixel.py
Modify default behavior of load_diffsky_healpixel.py and update docs
> Modify default behavior of load_diffsky_healpixel.py and update docs

- lsstdesc_diffsky/config_files/roman_rubin_2023_v0.2.0.yaml
- lsstdesc_diffsky/config_files/roman_rubin_2023_v0.2.1.yaml
- lsstdesc_diffsky/config_files/roman_rubin_2023_v0.3.0.yaml
- lsstdesc_diffsky/config_files/roman_rubin_2023_v0.3.1.yaml
- lsstdesc_diffsky/write_mock_to_disk_singlemet.py
- scripts/mock_production/run_diffsky_healpix_production.py
- scripts/mock_production/run_mpi_hpx_production.sh
Include changes for single met running
> Roman rubin v2 v3

- docs/source/demo_roman_rubin_2023_seds_singlemet.ipynb
- docs/source/demos.rst
Add docs for single-metallicity calculations
> Add docs for single-metallicity calculations

- lsstdesc_diffsky/write_mock_to_disk.py
- lsstdesc_diffsky/write_mock_to_disk_singlemet.py
- scripts/mock_production/submit_mpi_group.sh
removed incorrectly calculated major and minor axes columns
minor update to submit script to allow number of nodes to be specified if needed
> Remove major/minor axes; minor submit script update

- docs/source/rtd_environment.yaml
- lsstdesc_diffsky/param_data/tests/test_param_reader.py
- lsstdesc_diffsky/photometry/get_SEDs_from_SFH.py
- lsstdesc_diffsky/photometry/tests/test_photometry_lc_interp.py
- pyproject.toml
- requirements.txt
infer dependencies from requirements.txt from within pyprojec.toml
> infer dependencies from requirements.txt from within pyprojec.toml

- lsstdesc_diffsky/io_utils/load_diffsky_healpixel.py
Improve robustness of simple readiness test script
> Improve robustness of simple readiness test script

- scripts/individual_diffsky_photometry_script.py
Add script to calculate LSST and Roman magnitudes of individual galaxy
> Add script to calculate LSST and Roman magnitudes of individual galaxy

- lsstdesc_diffsky/size_modeling/tests/test_zhang_yang17.py
- lsstdesc_diffsky/size_modeling/zhang_yang17.py
Reduce scatter in size--luminosity relation to eliminate very-large-size outliers
cc @evevkovacs
> Reduce scatter in size--luminosity relation to eliminate very-large-size outliers

- lsstdesc_diffsky/disk_bulge_modeling/disk_bulge_kernels.py
- lsstdesc_diffsky/disk_bulge_modeling/tests/test_disk_bulge.py
- lsstdesc_diffsky/disk_bulge_modeling/tests/test_disk_knots.py
- lsstdesc_diffsky/dspspop/burstshapepop.py
- lsstdesc_diffsky/dspspop/photpop.py
- lsstdesc_diffsky/dspspop/tests/test_burstshapepop.py
- lsstdesc_diffsky/legacy/roman_rubin_2023/dsps/experimental/diffburst.py
- lsstdesc_diffsky/legacy/roman_rubin_2023/dsps/experimental/tests/test_diffburst.py
- lsstdesc_diffsky/legacy/roman_rubin_2023/dsps/utils.py
- lsstdesc_diffsky/photometry/photometry_lc_interp.py
- lsstdesc_diffsky/photometry/photometry_lc_interp_singlemet.py
- lsstdesc_diffsky/photometry/tests/test_photometry_lc_interp.py
- lsstdesc_diffsky/photometry/tests/test_photometry_lc_interp_singlemet.py
- lsstdesc_diffsky/sed/disk_bulge_sed_kernels.py
- lsstdesc_diffsky/sed/disk_bulge_sed_kernels_singlemet.py
- lsstdesc_diffsky/sed/sed_kernels.py
- lsstdesc_diffsky/sed/sed_kernels_singlemet.py
Migrate old version of diffburst into legacy.roman_rubin_2023
> Migrate old version of diffburst into legacy.roman_rubin_2023

- lsstdesc_diffsky/config_files/roman_rubin_2023_v1.1.2.yaml
- lsstdesc_diffsky/size_modeling/zhang_yang17.py
- lsstdesc_diffsky/write_mock_to_disk.py
- lsstdesc_diffsky/write_mock_to_disk_singlemet.py
and clipped galaxy sizes to 60.
> Bright sat fix

- docs/source/rtd_environment.yaml
- lsstdesc_diffsky/photometry/photometry_kernels.py
- lsstdesc_diffsky/photometry/photometry_kernels_singlemet.py
- requirements.txt
> try pinning to jax=0.4.20
